import "./globals.css";

import SidebarWrapper from "@/components/SidebarWrapper";
import { AuthContextProvider } from "@/context/AuthContext";
import {  ChildrenProp } from "@/types";
import { LanguageProvider } from "./Assignment-2/Context/LanguageContext";
import { ThemeProvider } from "./Assignment-2/Context/ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: ChildrenProp) => {
  return (
    <html lang="en">
        <body style={bodyStyle}>
          <aside style={sidebarStyle}>
            <h2 style={{ fontSize: "22px", marginBottom: "20px" }}>Assignments</h2>
            <nav style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
              <SidebarWrapper />
            </nav>
          </aside>
          <main style={{ padding: '20px' }}>
            <AuthContextProvider>
              <LanguageProvider>
                <ThemeProvider>
                {children}
                </ThemeProvider>
                </LanguageProvider>
            </AuthContextProvider>
          </main>
        </body>
    </html>
  );
};


const bodyStyle: React.CSSProperties = {
  display: "flex",
  flexDirection: "row",
  minHeight: "100vh",
  margin: 0,
  padding: 0,
};

const sidebarStyle: React.CSSProperties = {
  width: "240px",
  backgroundColor: "#1e293b",
  color: "white",
  padding: "20px",
  boxSizing: "border-box",
  flexShrink: 0, // Prevent sidebar from shrinking
};

const mainContentStyle: React.CSSProperties = {
  flex: 1,
  padding: "40px",
  boxSizing: "border-box",
  backgroundColor: "#f9fafb",
};

export default RootLayout;
